### ISSUE TITLE
Question: Mido

### ISSUE THREAD

**Issue by truefriend-cz** [dracarys18/NotKernel#1]
Hi. It is NotKernel-Raphael-2020-11-30-42-signed.zip for mido device? If it is... for what version? 3.14, 4.xx kernel?

**Comment by uditkarode** [comment]
It's for iPhone 4, version 6.9

**Comment by eldinesh** [comment]
I think this is for Apple's new M1 MacBook I'll try it.

**Comment by xCuri0** [comment]
works on my hp pavilion g7 powered by the quad core amd a8-4500m processor probably on mido too

**Comment by NeverSm1le** [comment]
> Hi. It is NotKernel-Raphael-2020-11-30-42-signed.zip for mido device? If it is... for what version? 3.14, 4.xx kernel?

Funny you use the mido name but don't know about raphael

**Comment by SahilSonar** [comment]
Ooo its all pro conversation
