### ISSUE TITLE
No commits for latest releases

### ISSUE THREAD

**Issue by mrmathematica** [dracarys18/NotKernel#2]
I see no commits/code change, but 2 latest releases (R20 & R21) with log claiming things like "Merged the latest CAF tag". 

All three latest releases are all tagged on cfa26d4, which can't be right.

**Comment by dracarys18** [comment]
That latest commit is for R19 mate, Source is not public yet because the commit history is slightly messed up, Here's the "Merged the latest CAF tag" commit you are looking for

![image](https://user-images.githubusercontent.com/43412619/115364718-4f97e400-a1e1-11eb-97cb-289c4dc789f5.png)

**Comment by dracarys18** [comment]
So as your concern is cleared I am closing this issue .

**Comment by mrmathematica** [comment]
My concern is that all new stuff has no source released. You are saying source is not public yet, which only confirms my concern, not addressing anything.
